apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera
spec:
  selector:
    matchLabels:
      app: camera
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: camera
    spec:
      hostNetwork: true
      containers:
      - name: camera
        image: kkasravi/camera:v1
        env:
        - name: DISPLAY
          value: ":0"
        securityContext:
          privileged: true
