apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-listener
spec:
  selector:
    matchLabels:
      app: mosquitto-listener
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: mosquitto-listener
    spec:
      containers:
      - name: mosquitto-listener
        image: kkasravi/mosquitto-listener:v1
